/**
 * The generated documentation written into an archive.
 *
 * Deliberately a fixed string with no interpolation — no project name, no date, no counts.
 * Exporting the same project twice must produce byte-identical archives, which is what lets
 * this format be compared, diffed, or committed without spurious changes.
 *
 * Named README.md rather than AGENTS.md on purpose. AGENTS.md is an instruction surface that
 * coding agents load as directives for the files beneath it, so a generated one would override
 * whatever conventions the reader already has. This is documentation, not instructions.
 */
export const SERVER_README_MD = `# Server functions in this archive

This folder is generated by OSW Studio when you download a project. **Edits to this file are
not preserved** — it is rewritten on every download. The files alongside it *are* yours to edit.

## Layout

    edge-functions/
      send-email.js      the function body
      send-email.json    its settings
    server-functions/
      formatPrice.js
      formatPrice.json
    secrets.json         names and descriptions only
    scheduled.json       cron schedules

Each function is a pair: a \`.js\` file holding the code, and a \`.json\` sibling of the same name
holding everything else — the HTTP method, whether it is enabled, its timeout, its description.
Change behaviour by editing the \`.js\`. Change how it is invoked by editing the \`.json\`.

## Writing function code

The code in a \`.js\` file is a **function body, not a module**. It runs inside an async wrapper,
so \`await\` works at the top level, but \`export\`, \`import\` and a surrounding \`function\` do not —
they are a syntax error. Return a result by calling \`Response\`:

    const body = typeof request.body === 'string' ? JSON.parse(request.body) : request.body;
    if (!body.email) {
      Response.json({ error: 'Missing email' }, 400);
      return;
    }
    db.run('INSERT INTO signups (email) VALUES (?)', [body.email]);
    Response.json({ ok: true });

Available in scope: \`request\`, \`Response\`, \`db\`, \`secrets\`, \`server\`, \`console\`, \`fetch\`,
\`btoa\`, \`atob\`, and \`crypto\` — the last being a two-function helper, \`crypto.sha256(text)\` and
\`crypto.randomUUID()\`, not the browser's Web Crypto API.

## Calling a server function

Everything in \`server-functions/\` is reachable from an edge function under \`server\`, by the name
its files use:

    const total = server.formatPrice(items, currency);

A server function's own code is a body too, and it receives \`args\` — an array of whatever the
caller passed — along with \`db\`:

    const [items, currency] = args;
    return items.reduce((sum, item) => sum + item.price, 0) + ' ' + currency;

Only enabled server functions are loaded, and they are not routable on their own: an edge function
is the only way in.

## Adding a function

Add both files. A \`.js\` with no \`.json\` is accepted and takes the defaults (method \`ANY\`,
enabled, 5000 ms timeout). A \`.json\` with no \`.js\` is an error — there is no code to run.

Names have to satisfy the same rules the app enforces: lowercase letters, numbers and hyphens
for edge functions and schedules; a JavaScript identifier for server functions; upper snake case
for secrets. A name that breaks those rules is reported when you import, not silently corrected.

## Secrets

\`secrets.json\` carries names and descriptions and **never values** — an archive leaves your
machine, so nothing secret goes into it. Importing creates the entries empty; fill them in under
Project settings before publishing. Adding a \`value\` here does nothing.

## Schedules

\`scheduled.json\` refers to an edge function by name rather than by id, so a schedule keeps
working when the archive is imported into a different project. The named function has to exist,
either already in the target project or elsewhere in this archive.
`;
